// Copyright 2022-2024 The MathWorks, Inc.
// Generated 31-Jan-2026 01:10:15
#include "slros2_initialize.h"
// rover_sw_pwrtrain_24b/ros_publish/Publish1
SimulinkPublisher<std_msgs::msg::Int32,SL_Bus_std_msgs_Int32> Pub_rover_sw_pwrtrain_24b_907;
// rover_sw_pwrtrain_24b/ros_publish/Publish10
SimulinkPublisher<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Pub_rover_sw_pwrtrain_24b_1122;
// rover_sw_pwrtrain_24b/ros_publish/Publish2
SimulinkPublisher<std_msgs::msg::Int32,SL_Bus_std_msgs_Int32> Pub_rover_sw_pwrtrain_24b_826;
// rover_sw_pwrtrain_24b/ros_publish/Publish3
SimulinkPublisher<std_msgs::msg::Int32,SL_Bus_std_msgs_Int32> Pub_rover_sw_pwrtrain_24b_246;
// rover_sw_pwrtrain_24b/ros_publish/Publish4
SimulinkPublisher<std_msgs::msg::Int32,SL_Bus_std_msgs_Int32> Pub_rover_sw_pwrtrain_24b_1006;
// rover_sw_pwrtrain_24b/ros_publish/Publish5
SimulinkPublisher<std_msgs::msg::Int32,SL_Bus_std_msgs_Int32> Pub_rover_sw_pwrtrain_24b_903;
// rover_sw_pwrtrain_24b/ros_publish/Publish6
SimulinkPublisher<std_msgs::msg::Int32,SL_Bus_std_msgs_Int32> Pub_rover_sw_pwrtrain_24b_1009;
// rover_sw_pwrtrain_24b/ros_publish/Publish7
SimulinkPublisher<std_msgs::msg::Int32,SL_Bus_std_msgs_Int32> Pub_rover_sw_pwrtrain_24b_1039;
// rover_sw_pwrtrain_24b/ros_publish/Publish8
SimulinkPublisher<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Pub_rover_sw_pwrtrain_24b_1087;
// rover_sw_pwrtrain_24b/ros_publish/Publish9
SimulinkPublisher<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Pub_rover_sw_pwrtrain_24b_1115;
// rover_sw_pwrtrain_24b/trailhead_main/motor_controls/Subsystem2/Publish1
SimulinkPublisher<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Pub_rover_sw_pwrtrain_24b_1057;
// rover_sw_pwrtrain_24b/trailhead_main/motor_controls/Subsystem2/Publish2
SimulinkPublisher<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Pub_rover_sw_pwrtrain_24b_1058;
// rover_sw_pwrtrain_24b/trailhead_main/motor_controls/Subsystem2/Publish3
SimulinkPublisher<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Pub_rover_sw_pwrtrain_24b_1059;
// rover_sw_pwrtrain_24b/trailhead_main/motor_controls/Subsystem2/Publish4
SimulinkPublisher<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Pub_rover_sw_pwrtrain_24b_1060;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_390;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe1
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_391;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe10
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_1130;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe11
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_1131;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe12
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_1132;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe13
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_1133;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe2
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_392;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe3
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_986;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe4
SimulinkSubscriber<std_msgs::msg::Bool,SL_Bus_std_msgs_Bool> Sub_rover_sw_pwrtrain_24b_521;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe5
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_987;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe6
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_988;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe7
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_989;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe8
SimulinkSubscriber<std_msgs::msg::Float32,SL_Bus_std_msgs_Float32> Sub_rover_sw_pwrtrain_24b_1018;
// rover_sw_pwrtrain_24b/ros_subscribe/Subscribe9
SimulinkSubscriber<std_msgs::msg::Bool,SL_Bus_std_msgs_Bool> Sub_rover_sw_pwrtrain_24b_1042;
